### ISSUE TITLE
Does it support forwarding from the channels which we didnt joined

### ISSUE THREAD

**Issue by telegrambotdev** [keselekpermen69/Telegram_Forwarder#1]
Does it support forwarding from the channels which we didnt joined ?

**Comment by keselekpermen69** [comment]
yes it does
but it's necessary that the bot must be in both channel(as admin) and chat

**Comment by insoxin** [comment]
> Does it support forwarding from the channels which we didnt joined ?

Have you succeeded? I have the same needs.
