### ISSUE TITLE
ModuleNotFoundError: No module named 'auto_forwarder'

### ISSUE THREAD

**Issue by s-ahmadzadeh** [keselekpermen69/Telegram_Forwarder#10]
I create a config.py file as explained in readme .. when i run "python -m forwarder" give me a error : ModuleNotFoundError: No module named 'auto_forwarder'

**Comment by keselekpermen69** [comment]
That first line import should be `from forwarder.sample_config import Config`.
Forgot to change that.

**Comment by jerung3000** [comment]
Hi keselekpermen69.

When i tried to run your repo..I get this error..

File "C:\PYTHON\Telegram_Forwarder\Telegram_Forwarder\forwarder\__init__.py", line 4, in <module>
    import telegram.ext as tg
ModuleNotFoundError: No module named 'telegram'

**Comment by keselekpermen69** [comment]
@jerung3000 you need to install the requirements first
```pip install -r requirements.txt```

**Comment by jerung3000** [comment]
ok..already install..when I run python -m forwarder
 there were statements show like this 

C:\PYTHON\Telegram_Forwarder\Telegram_Forwarder>python -m forwarder
The README is there to be read. Extend this sample config to a config file, don't just rename and change values here. Doing that WILL backfire on you.
Bot quitting.

**Comment by keselekpermen69** [comment]
then go read the [**README**](https://github.com/keselekpermen69/Telegram_Forwarder#configuration).

**Comment by jerung3000** [comment]
ok..already follow the step but there were statements show like this

C:\PYTHON\Telegram_Forwarder\Telegram_Forwarder>python -m forwarder
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\PYTHON\Telegram_Forwarder\Telegram_Forwarder\forwarder\__init__.py", line 42, in <module>
    from forwarder.config import Development as Config
ModuleNotFoundError: No module named 'forwarder.config'

**Comment by shad0w-cat** [comment]
Locate the Forwarder folder.
Open Command Prompt /Powershell there 
Then use this command python forwarder.py
