### ISSUE TITLE
should the bot be admin?

### ISSUE THREAD

**Issue by s-ahmadzadeh** [keselekpermen69/Telegram_Forwarder#13]
I want to send messages from a specific channel to another channel (my own channel), is this necessary to add bot to both of the channels?
I can not add the bot as an admin to the source channel (from), but I can add the bot as an admin to the destination channel (to) which is my own channel

**Comment by keselekpermen69** [comment]
yeahh...
the bot need a message access to the chat (Admin if it's a channel) unless it wouldn't work
