### ISSUE TITLE
Forwarded messages return as forwarded 

### ISSUE THREAD

**Issue by TWIISTED-STUDIOS** [keselekpermen69/Telegram_Forwarder#20]
Is it possible so that when messages are forwarded it stops all the data of the orignal message so when it is moved to another location it no longer says forwarded from. .....

**Comment by keselekpermen69** [comment]
I assume you want to do this #15

**Comment by TWIISTED-STUDIOS** [comment]
That is correct I wish to do that, but I have it hosted on heroku where would I begin to do that?

**Comment by keselekpermen69** [comment]
just edit on your forked repo & deploy that

**Comment by TWIISTED-STUDIOS** [comment]
@keselekpermen69 ok then thank you I will try that and see how that works
