### ISSUE TITLE
can we change the script ? instead using the bot as forwarder, we using our main account as forwarder, is it possible ?

### ISSUE THREAD

**Issue by ycuranxiety** [keselekpermen69/Telegram_Forwarder#3]

**Comment by keselekpermen69** [comment]
It's not possible with the bot api. You might have to take a look to userbot. Take a look to libraries like [telethon](https://github.com/LonamiWebs/Telethon) or [pyrogram](https://github.com/pyrogram/pyrogram) for userbot.

**Comment by ycuranxiety** [comment]
which code should i change ? or i should make a new project with userbot ?

**Comment by keselekpermen69** [comment]
It's totally different library so make a new project about it

**Comment by nvdp778** [comment]
Bro it's possible the devloper can't know  message me at telegram  @raoji51
