### ISSUE TITLE
No module named 'forwarder.config'

### ISSUE THREAD

**Issue by jerung3000** [keselekpermen69/Telegram_Forwarder#33]
Hi keselekpermen69

I already follow the step but there were an error show like this

C:\PYTHON\Telegram_Forwarder\Telegram_Forwarder>python -m forwarder
Traceback (most recent call last):
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 188, in _run_module_as_main
mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 147, in _get_module_details
return _get_module_details(pkg_main_name, error)
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 111, in get_module_details
import(pkg_name)
File "C:\PYTHON\Telegram_Forwarder\Telegram_Forwarder\forwarder_init.py", line 42, in
from forwarder.config import Development as Config
ModuleNotFoundError: No module named 'forwarder.config'

**Comment by keselekpermen69** [comment]
Please **read the [README](https://github.com/keselekpermen69/Telegram_Forwarder#configuration)**. All information was clearly described there and I have answer it on #28 . Or here i give you more clear steps

1.  **Create a new** `config.py` file  (at the same level with sample_config.py) **not renaming** the `sample_config.py.`.
```
/YourFileName
├── /forwarder
│   └── /modules
│   └── __init__.py
│   └── __main__.py
│   └── sample_config.py
│   └── config.py   <-------- CREATE YOUR OWN CONFIG FILE HERE(DON'T RENAME THE sample_config.py)!
├── LICENSE
├── README.md
├── ....
```

2. **Put your variables like the one on the README**.
Here the example to be more clear (this thing already described on README)
```python
from forwarder.sample_config import Config  # <----- Don't forget this thing

class Development(Config):
    API_KEY = ""  # Your bot API key
    OWNER_ID =  # Your user id make it an integer (don't give a quote)

    # Make sure to include the '-' sign in group and channel ids.
    FROM_CHATS = [-1001234567890]  # List of chat id's to forward messages from (don't give quote).
    TO_CHATS = [-1001234567890, -1234567890]  # List of chat id's to forward messages to (don't give quote).
    
    WORKERS = 4
```

3. Install the necessary python dependencies by moving to the project.
You can run `pip install -r requirements.txt`.

4. Then its all done you can run `python -m forwarder`
