### ISSUE TITLE
Support for bot pm message forwarding to group chats?

### ISSUE THREAD

**Issue by marchingon12** [keselekpermen69/Telegram_Forwarder#4]
Is it possible to forward bot messages to group chats? For example, if the IFTTT bot sends me a message, and I want to forward the message to a group chat, would it be possible?

**Comment by keselekpermen69** [comment]
The only way for the bot to see other bot's message is through a channel. If you can manage that IFTTT bot to send the message on a channel you are good else. I think in this case it possible by using UserBot on your account to handle the other bot that sends you a message and forward it with the bot on the group chat or with your account(with that UserBot).

**Comment by marchingon12** [comment]
Yeah I thought about that too. The only way seems to be using a userbot to forward the message from IFTTT's bot pm as soon as it is received to the channel/group. Do you think it will be easy to port your module to something like FTG Userbot?

**Comment by keselekpermen69** [comment]
depends on you ><
