### ISSUE TITLE
Remove API key from repo!

### ISSUE THREAD

**Issue by marchingon12** [keselekpermen69/Telegram_Forwarder#5]
https://github.com/keselekpermen69/Telegram_Forwarder/blob/807d3015257022d8c76dabeaa91d0cacc6e93ae0/forwarder/sample_config.py#L13

Remove your Bot API from the repo, or else people can mess with your bot or change it completely.

**Comment by keselekpermen69** [comment]
Thanks for the notice.

All variables in sample_config was just a placeholder to help with the data type.
