### ISSUE TITLE
i Create a config.py file but it does not work

### ISSUE THREAD

**Issue by MiniMamini01** [keselekpermen69/Telegram_Forwarder#9]
I create a config.py file and copy class Config from sample_config in it .. and replace my token in config.py .. when i run "python -m forwarder" give me a error :  " ModuleNotFoundError: No module named 'sample_config "

**Comment by keselekpermen69** [comment]
Read the readme file!
config file should be placed in forwarder folder.
you just have to modify the variable don't delete the production and development class below.
